version: 2
jobs:
  gcc-u20.04-mrpt-dev:
    docker:
      - image: mrpt/mrpt-build-env:full-focal
    steps:
      - run:
          name: "Install dependencies"
          command: |
            apt-get update
            apt-get install software-properties-common -y
            add-apt-repository ppa:joseluisblancoc/mrpt -y
            apt-get install libmrpt-dev -y
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Generate cmake files
          command: cmake -H. -Bbuild
      - run: make -C build
      - run: make CTEST_OUTPUT_ON_FAILURE=1 test -C build
#      - run: make gcov -C build
#      - run: make -C build
#      - run: bash <(curl -s https://codecov.io/bash) -X gcov -y .codecov.yml -s build
  gcc-u20.04-mrpt-stable:
    docker:
      - image: mrpt/mrpt-build-env:full-focal
    steps:
      - run:
          name: "Install dependencies"
          command: |
            apt-get update
            apt-get install software-properties-common -y
            add-apt-repository ppa:joseluisblancoc/mrpt-stable -y
            apt-get install libmrpt-dev -y
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Generate cmake files
          command: cmake -H. -Bbuild
      - run: make -C build
      - run: make CTEST_OUTPUT_ON_FAILURE=1 test -C build
  clang-u20.04-mrpt-dev:
    docker:
      - image: mrpt/mrpt-build-env:full-focal
    steps:
      - run:
          name: "Install dependencies"
          command: |
            apt-get update
            apt-get install software-properties-common -y
            add-apt-repository ppa:joseluisblancoc/mrpt -y
            apt-get install libmrpt-dev -y
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Generate cmake files
          command: cmake -H. -Bbuild
          environment:
            CC: /usr/bin/clang-9
            CXX: /usr/bin/clang++-9
      - run: make -C build
      - run: make CTEST_OUTPUT_ON_FAILURE=1 test -C build
workflows:
  version: 2
  build:
    jobs:
      - gcc-u20.04-mrpt-dev
      - gcc-u20.04-mrpt-stable
      - clang-u20.04-mrpt-dev
